#!/bin/bash
DEBUG=true
#import settings
source settings.conf

### change this for different syncs ###
SOURCE="DEV"
DESTINATION="TEST"

#build the relevant variables for this sync
createVariables

##meat and bones of this script
syncSystems